---
- name: Windows playbook to check user and group
  hosts: all
  gather_facts: false
  become: false
  tasks:
  - name: Perform a basic ping
    ansible.windows.win_ping:

  - name: Run whoami in PS
    ansible.windows.win_shell: whoami
    register: default_win_user

  - name: Display Default windows user
    ansible.builtin.debug:
      var: default_win_user.stdout

  - name: Get list of all groups user is a member of
    ansible.windows.win_shell: $DN = (Get-ADUser -Identity "{{ansible_user }}" -Properties DistinguishedName).DistinguishedName Get-ADGroup -LDAPFilter "(member:1.2.840.113556.1.4.1941:=$($DN))"
    register: my_groups

  - name: Display groups
    debug:
      var: my_groups.stdout_lines

  - name: Fail if not in administrators group
    fail:
      msg: failed
    when: "'Name              : Administrators' not in my_groups.stdout_lines"
